version: "3.0"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "19003:19003"
    environment:
      - SERVICES=dynamodb:19003
      - START_WEB=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
