version: "3.0"
services:
  mysql:
    image: "mysql:5.7"
    env_file:
      .env
    ports:
      - "19002:3306"

  bind9:
    image: "vinyldns/bind9:0.0.4"
    env_file:
      .env
    ports:
      - "19001:53/udp"
      - "19001:53"
    volumes:
      - ./bind9/etc:/var/cache/bind/config
      - ./bind9/zones:/var/cache/bind/zones

  localstack:
    image: localstack/localstack
    ports:
      - "19000:19000"
      - "19006:19006"
      - "19007:19007"
    environment:
      - SERVICES=dynamodb:19000,sns:19006,sqs:19007
      - START_WEB=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

  mail:
    image: flaviovs/mock-smtp
    ports:
      - "19025:25"
    volumes:
      - ./email:/var/lib/mock-smtp
